spring:
  datasource: # mysql\u76F8\u5173\u914D\u7F6E
    url: jdbc:mysql://liboshuai.mysql.rds.aliyuncs.com:58107/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Rongshu@2023
    druid:
      initial-size: 5 #\u8FDE\u63A5\u6C60\u521D\u59CB\u5316\u5927\u5C0F
      min-idle: 10 #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      max-active: 20 #\u6700\u5927\u8FDE\u63A5\u6570
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #\u4E0D\u7EDF\u8BA1\u8FD9\u4E9B\u8BF7\u6C42\u6570\u636E
      stat-view-servlet: #\u8BBF\u95EE\u76D1\u63A7\u7F51\u9875\u7684\u767B\u5F55\u7528\u6237\u540D\u548C\u5BC6\u7801
        login-username: druid
        login-password: druid

  redis: # redis\u76F8\u5173\u914D\u7F6E
    host: liboshuai.redis.rds.aliyuncs.com
    database: 0
    port: 58108
    password: ENC(+cJyhlOeoBf+vV5SMp4B/EaLVzpAhBsa)
    timeout: 300
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  rabbitmq: # rabbitmq\u76F8\u5173\u914D\u7F6E
    host: 1.117.233.154
    port: 18672
    virtual-host: /mall
    username: liboshuai01
    password: BI13sOOHhdSJHGL
    publisher-confirm-type: CORRELATED

elasticSearch: # elasticSearch\u76F8\u5173\u914D\u7F6E
  scheme: http
  host: 1.117.233.154
  port: 18200
  userName: elastic
  password: Rongshu@2023