spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: '@env@'

server:
  port: 8081
  servlet:
    context-path: /mall-tiny
config:
  accessToken-expireTime: 86400
  encrypt-jwtKey: gHMzjdlP84njamo29YgoAjpH
  refreshToken-expireTime: 604800
  shiro-cache-expireTime: 600

redis:
  key:
    expire:
      authCode: 60
    prefix:
      authCode: "portal:authCode:"

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml

logging:
  config: classpath:logback-spring.xml

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator



