spring:
  data:
    elasticsearch:
      cluster-nodes: j.jyy.cool:18300
  datasource:
    password: ENC(UA/LixCFWVP+XC7lAvfGpsq2m9T8xQvt)
    url: jdbc:mysql://liboshuai.mysql.rds.aliyuncs.com:58107/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
  redis:
    database: 0
    host: liboshuai.redis.rds.aliyuncs.com
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    password: ENC(+cJyhlOeoBf+vV5SMp4B/EaLVzpAhBsa)
    port: 58108
    timeout: 300
